# Generated by Django 5.2.4 on 2025-08-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('website', models.URLField(blank=True, help_text='Your website or portfolio URL')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Main content of the post')),
                ('excerpt', models.TextField(blank=True, help_text='Brief description of the post', max_length=300)),
                ('category', models.CharField(blank=True, choices=[('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('food', 'Food'), ('health', 'Health'), ('business', 'Business'), ('education', 'Education'), ('entertainment', 'Entertainment')], max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.users')),
            ],
        ),
    ]
