# Generated by Django 5.2.4 on 2025-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='default', help_text='Unique username for login', max_length=150, unique=True),
        ),
    ]
