# Generated by Django 5.2.4 on 2025-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_users_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', help_text="User's email address", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', help_text="User's first name", max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', help_text="User's last name", max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, help_text='User opted for newsletter'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', help_text='Hashed password', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(help_text='Unique username for login', max_length=150, unique=True),
        ),
    ]
