# Generated by Django 5.2.4 on 2025-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_users_options_users_email_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('can_publish_post', 'Can publish posts'), ('can_feature_post', 'Can feature posts'), ('can_moderate_post', 'Can moderate posts')]},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('can_manage_users', 'Can manage all users'), ('can_manage_all_posts', 'Can manage all posts'), ('can_view_analytics', 'Can view site analytics')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('author', 'Author')], default='author', help_text='User role for access control', max_length=10),
        ),
    ]
