# Generated by Django 5.2.4 on 2025-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_alter_users_options_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, help_text='Number of views'),
        ),
    ]
